name: bookwormy
description: "A simple book tracking app"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.0-24.0.dev
dependencies:
  flutter:
    sdk: flutter

  sqflite: ^2.0.0+4
  sqflite_common_ffi: ^2.0.0+4
  path: ^1.8.0
  http: any
  path_provider: any
  file_picker: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
